Update issue templates
procurify/flag-counter pull request #10
Opened 2021-03-24 23:48 UTC by kenzyop

Adding an issue template

2021-03-24 23:51 UTC, rocpoon approved these changes
Looks good

2021-03-24 23:53 UTC, rocpoon approved these changes
Looks even better now, awesome

2021-03-24 23:57 UTC, SoJexy approved these changes
@kenzyop Looks good to me 👍🏻

2021-03-24 23:59 UTC, AndyHsiungDev requested changes

2021-03-24 23:59 UTC, AndyHsiungDev commented on .github/ISSUE_TEMPLATE/issue-report.md
> +A clear and concise description of what the bug is.
Is this supposed to be different from a bug report? Perhaps this template should be a "Feature Request" instead.

2021-03-25 00:06 UTC, AndyHsiungDev approved these changes

2021-03-25 00:07 UTC, merged